//Different Stages
var MENU_STAGE = "menu";
var GAME_STAGE = "game";

// Menu Coordinates
var SQUARE_LENGTH = 50;
var GRID_SIZE = 10;
var GRID_WIDTH_BOUND = SQUARE_LENGTH * GRID_SIZE; 
var GRID_HEIGHT_BOUND = SQUARE_LENGTH * GRID_SIZE; 
var GRID_PADDING = 10;
var TIMER_HEIGHT = 40;
var TIMER_PADDING = 10;
var TIMER_LENGTH = GRID_WIDTH_BOUND;

var TIMER_LOCATION_X = GRID_PADDING;
var TIMER_LOCATION_Y = GRID_HEIGHT_BOUND + (GRID_PADDING * 2) + 1

var GAME_OVER_TEXT_X = GRID_PADDING;
var GAME_OVER_TEXT_Y = GRID_HEIGHT_BOUND + (GRID_PADDING * 2) + 10;

var RETRY_BUTTON_WIDTH = 100;
var RETRY_BUTTON_HEIGHT = 40;
var RETRY_BUTTON_X = (GRID_PADDING*2 + GRID_WIDTH_BOUND)/2 - RETRY_BUTTON_WIDTH/2;
var RETRY_BUTTON_Y = GRID_HEIGHT_BOUND + (GRID_PADDING*2) ;

var ADD_SECONDS_BUTTON_X = GRID_PADDING;
var ADD_SECONDS_BUTTON_Y = GRID_HEIGHT_BOUND + (GRID_PADDING * 2) +TIMER_HEIGHT+TIMER_PADDING;

var ADD_SECONDS_BUTTON_WIDTH = 150;
var ADD_SECONDS_BUTTON_HEIGHT = 40;
var ADD_SECONDS_BUTTON_PADDING = 10

var CANVAS_WIDTH = GRID_WIDTH_BOUND + (GRID_PADDING * 2) + 1;
var CANVAS_HEIGHT = GRID_HEIGHT_BOUND + (GRID_PADDING * 2) + 1 + TIMER_HEIGHT + TIMER_PADDING + ADD_SECONDS_BUTTON_HEIGHT + ADD_SECONDS_BUTTON_PADDING;

var EASY_BUTTON_X = CANVAS_WIDTH/2 - 250/2;
var EASY_BUTTON_Y = 200;
var EASY_BUTTON_TEXT_X = EASY_BUTTON_X + 105;
var EASY_BUTTON_TEXT_Y = EASY_BUTTON_Y + 30;

var MEDIUM_BUTTON_X = EASY_BUTTON_X;
var MEDIUM_BUTTON_Y = 300;
var MEDIUM_BUTTON_TEXT_X = MEDIUM_BUTTON_X + 95;
var MEDIUM_BUTTON_TEXT_Y = MEDIUM_BUTTON_Y + 30;

var HARD_BUTTON_X = EASY_BUTTON_X;
var HARD_BUTTON_Y = 400;
var HARD_BUTTON_TEXT_X = HARD_BUTTON_X + 105;
var HARD_BUTTON_TEXT_Y = HARD_BUTTON_Y + 30;

var MENU_BUTTON_LENGTH = 250;
var MENU_BUTTON_HEIGHT = 50;

//Colors
var WHITE = "rgb(255,255,255)";
var RED = "rgb(255, 0, 0)";
var ORANGE = "rgb(255, 128, 0)";
var YELLOW = "rgb(255, 255, 0)";
var GREEN = "rgb(0, 255, 0)";
var CYAN = "rgb(0, 255, 255)";
var LIGHTBLUE = "rgb(0, 128,255)";
var BLUE = "rgb(0, 0, 255)";
var PURPLE = "rgb(127, 0 , 255)";
var PINK = "rgb(255, 0 , 127)";
var BURNTUMBER = "rgb(138, 52, 36)";
var BLACK = "rgb(0,0,0)";

var BOX_SELECTION_COLOR = "#FF0000";

var COLOR_ARRAY = [ORANGE,YELLOW, GREEN, CYAN, LIGHTBLUE, BLUE, PURPLE, PINK, BURNTUMBER];


//Game Constants
var BEND_NUMBER = 3;
var NUM_ADD_SECONDS = 3;
var SECONDS_ADDED = 5;

var MOVE_TOP = "t";
var MOVE_BOTTOM = "b";
var MOVE_RIGHT = "r";
var MOVE_LEFT = "l";

var EMPTY = 0;

var EASY = 4;
var MEDIUM = 6;
var HARD = 8;
